# simple script to removce files generated by tutorial
rm attenuation_simind* 
rm attenuation_stir* 
rm attenuation_none* 
rm emission_image*
rm output*
rm *.png
rm tumour.inp
rm *.hv
rm *.ahv
rm *.v
rm simind.smc